server:
  port: 8802

spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
  liquibase:
    enabled: ${LIQUIBASE_ENABLED}
    change-log: classpath:/db/changelog/db.changelog-master.yml

#file related configuration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


